.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-MAS\-APPSTORE" "1" "October 2012" "" ""
.
.SH "NAME"
\fBfhc-mas-appstore\fR \-\- View your Mobile App Store
.
.SH "SYNOPSIS"
.
.nf
fhc admin\-auditlog listlogs [limit=<limit>] [guid=<store item guid>] [type=<android|iphone>] [user=<user guid>] [device=<device guid>]
   when filters (such as guid and type) are supplied then the log entry must match ALL of the filters\.
   when no limit is supplied, it defaults to 20
.
.fi
.
.SH "DESCRIPTION"
This command allows you to View your FeedHenry Mobile App Store Audit Logs\. See http://docs\.feedhenry\.com/v2/mas\.html for more information\.
