.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-ADMIN\-USERS" "1" "August 2012" "" ""
.
.SH "NAME"
\fBfhc-admin-users\fR \-\- Administer FeedHenry Users
.
.SH "SYNOPSIS"
.
.nf
fhc admin\-users list
fhc admin\-users create username=<username> [password=<password>] [email=<email>] [name=<name>] [roles=<roles>] [authpolicies=<authpolicies>] [invite=<invitation>]
fhc admin\-users delete <username>
fhc admin\-users read <username>
fhc admin\-users update username=<username> [password=<password>] [email=<email>] [name=<name>] [roles=<roles>] [authpolicies=<authpolicies>] [inviation=<invitation>] [enabled=<enabled>]
fhc admin\-users enable <username>
fhc admin\-users disable <username>
fhc admin\-users changeroles <username> <roles>
fhc admin\-users changeauthpolicies <username> <authpolicies>
fhc admin\-users listdevices <username>
fhc admin\-users listinstallapps <username>
fhc admin\-users import <path\-to\-csv\-file> [invite] [<roles> <authpolicies>]
.
.fi
.
.SH "DESCRIPTION"
This command allows you to Administer Users on the FeedHenry Platform\. For more information, see http://docs\.feedhenry\.com/v2/useradmin\.html\.
