.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-ADMIN\-APPSTORE" "1" "August 2012" "" ""
.
.SH "NAME"
\fBfhc\-admin\-appstore\fR \- Administer your App Store
.
.SH "SYNOPSIS"
.
.nf

fhc admin\-appstore list
fhc admin\-appstore read
fhc admin\-appstore update <name> <description> <appid1,apppid2>
fhc admin\-appstore updatefield <fieldname> <fieldvalue>
fhc admin\-appstore listitems
fhc admin\-appstore additem <StoreItem Guid>
fhc admin\-appstore removeitem <StoreItem Guid>
fhc admin\-appstore listpolicies
fhc admin\-appstore addpolicy <policyid>
fhc admin\-appstore removepolicy <policyid>
.
.fi
.
.SH "DESCRIPTION"
This command allows you to Administer your FeedHenry App Store\. See http://docs\.feedhenry\.com/v2/mas\.html for more information\.
