.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-ADMIN\-STOREITEMS" "1" "August 2012" "" ""
.
.SH "NAME"
\fBfhc\-admin\-storeitems\fR \- Administer Store Items
.
.SH "SYNOPSIS"
.
.nf

fhc admin\-storeitems list
fhc admin\-storeitems create <name> <description> <authToken>
fhc admin\-storeitems delete <storeitem guid>
fhc admin\-storeitems read <storeitem guid>
fhc admin\-storeitems update <storeitem guid> <name> <description> <authToken>
fhc admin\-storeitens uploadicon <storeitem guid> <path to icon>
fhc admin\-storeitems uploadbinary <storeitem guid> <type iphone|android|ipad> <path to app binary>
fhc admin\-storeitems addpolicy <storeitem guid> <policy_guid>
fhc admin\-storeitems removepolicy <storeitem guid> <policy_guid>
fhc admin\-storeitems listpolicies <storeitem guid>
.
.fi
.
.SH "DESCRIPTION"
This command allows you to Administer your FeedHenry App Store\. See http://docs\.feedhenry\.com/v2/mas\.html for more information\.
