.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-ALIAS" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-alias\fR \-\- FeedHenry Actions
.
.SH "SYNOPSIS"
.
.nf
fhc alias <app\-id>=<alias>
.
.fi
.
.SH "DESCRIPTION"
This is a utility command to set an alias for the 24 character appid 
.
.SS "app id"
Your application id\.
.
.SS "alias"
Simple name that is easy to remember
.
.SH "EXAMPLES"
.
.nf
fhc alias 2ifjg\-dsf343hjlo97dhnvh5=myapp
.
.fi

