.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-APPENDPOINTS" "1" "June 2014" "" ""
.
.SH "NAME"
\fBfhc-appendpoints\fR \-\- List Cloud App Endpoints
.
.SH "SYNOPSIS"
.
.nf
fhc appendpoints <app\-id> [dev|live]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to list all your Cloud Endpoints\.
.
.SH "Examples"
.
.nf
fhc appendpoints mfLkParVTDcr80\-uEk8OhEfT \-\-live
.
.fi

