.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-APPS" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-apps\fR \-\- Manage FeedHenry Applications
.
.SH "SYNOPSIS"
.
.nf
fhc apps 
fhc apps [read] <app\-id>
fhc apps create <app\-title> [<git\-repo> <git\-branch> <key\-file>]
fhc apps update <app\-id> <property\-name> <property\-value>
fhc apps delete <app\-id>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to manage your FeedHenry applications\.
