.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-APPS" "1" "June 2014" "" ""
.
.SH "NAME"
\fBfhc-apps\fR \-\- List FeedHenry Applications
.
.SH "SYNOPSIS"
.
.nf
fhc apps [list] <project\-id>
fhc create <project\-id> <app\-title> [<template\-id>]
fhc create <project\-id> <app\-title> <template\-type> <git\-repo> [<git\-branch>]
fhc read <project\-id> <app\-id>
fhc update <project\-id> <app\-id> <property\-name> <property\-value>
fhc delete <project\-id> <app\-id>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to list your FeedHenry applications\. As with any command in FHC, passing a \'\-\-json\' flag will return the list of FeedHenry Apps in JSON format\.
.
.P
You can also specify a \'\-\-bare\' flag to the \'apps\' command, e\.g\. just show app guids:
.
.P
$ fhc apps 123456 \-\-bare
.
.P
t2Xva0\-4X2AFsxbBzsRLSet1
VCtqRZTJWnhz5b3SbcS1LvVm
DOK1rO5L2WAW7fjE_MAIehio
t\-Bq8rCXHMwJSY9heXZZs8AL
.
.P
show app titles only:
.
.P
$ fhc apps 123456 \-\-bare=title
.
.P
App 1 
App 2
App 3
App 4
.
.P
This makes it easy to iterate over apps from bash command line, e\.g\. to ping all dev and live endpoints of all apps:
.
.P
$ for i in $(fhc apps \-\-bare);do echo "pinging: $i (dev & live)"; fhc ping $i; fhc ping $i \-\-live; done
