.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-BUILD" "1" "July 2012" "" ""
.
.SH "NAME"
\fBfhc\-build\fR \- Build FeedHenry Applications
.
.SH "SYNOPSIS"
.
.nf

fhc build app=<appId> destination=<destination> version=<version> config=<config>  stage=<true|false> keypass=<private\-key\-password> certpass=<certificate\-password> download=<true|false>
  where <destination> is one of: andriod, iphone, ipad, ios(for universal binary), blackberry, windowsphone7
  where <version> is specific to the destination (e\.g\. Android version 4\.0)
  where <config> is either \'debug\' (default), \'distribution\', or \'release\'
  where <stage> is either \'true\' or \'false\', default is false
  where <provisioning> is the path to the provisioning profile
  \'keypass\' and \'certpass\' only needed for \'release\' builds
  \'provisioning\' is only optional for iphone or ipad builds
.
.fi
.
.SH "DESCRIPTION"
This command can be used to build your FeedHenry applications\. If \'stage\' is set to \'true\', a server side stage of the app is done (if its a \'release\' or \'distriburion\' build, a Live stage is done, otherwise a Development stage)\.
.
.P
e\.g\. fhc build app=mfLkParVTDcr80\-uEk8OhEfT destination=iphone config=distribution keypass=password certpass= version=4\.0
