.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-CALL" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-call\fR \-\- FeedHenry Call Url
.
.SH "SYNOPSIS"
.
.nf
fhc call <url> [<method> <params>]
.
.fi
.
.SH "DESCRIPTION"
This command will call the specified FeedHenry url (using the given method or \'GET\' by default, and passing the given parameters, if any)
