.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-CF" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-cf\fR \-\- FeedHenry CloudFoundry
.
.SH "SYNOPSIS"
.
.nf
fhc cf apps
fhc cf app <app\-name>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to interact with the FeedHenry CloudFoundry backend\.
