.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-CHECKOUT" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-checkout\fR \-\- Checkout FeedHenry Applications Source
.
.SH "SYNOPSIS"
.
.nf
fhc checkout <app\-id> [directory]
.
.fi
.
.SH "DESCRIPTION"
For non Git based projects, checkout can be used to download an Applications source code\. If no directory is specified the current directory is assumed\.
