.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-CLOUDFOUNDRY" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-cloudfoundry\fR \-\- FeedHenry CloudFoundry
.
.SH "SYNOPSIS"
.
.nf
fhc cloudfoundry <app\-id> <cf\-target> <cf\-user> <cf\-pwd>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to set the CloudFoudry live staging target for an app\. \'cf target\' should be your CloudFoundry target (same as you use in VMC), and \'cf user/ cf pwd\' should be your CloudFoundry login credentials for that target\.
.
.SH "Examples"
.
.nf
fhc cloudfoundry 123456789012345678901234 http://api\.cloudfoundry\.com foo@bar\.com password
.
.fi

