.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-CONFIGURATION" "1" "November 2011" "" ""
.
.SH "NAME"
\fBfhc-configuration\fR \-\- Manage Application Configuration Properties
.
.SH "SYNOPSIS"
fhc configuration (list) <app id>
fhc configuration (list) <app id> <destination>
fhc configuration set <app id> <destination> <key> <value>
.
.P
where destination can be one of: studio, android, embed, iphone, ipad, blackberry, windowsphone7, nokiawrt or \'all\'
.
.SH "DESCRIPTION"
This command can be used to manage an Applications Destination Configuration properties\.
