.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-CREATE" "1" "April 2012" "" ""
.
.SH "NAME"
\fBfhc-create\fR \-\- Create FeedHenry Applications
.
.SH "SYNOPSIS"
.
.nf
fhc create <app\-title> [<git\-repo> <git\-branch>]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to create a new FeedHenry Application\.
