.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-EMBED" "1" "June 2014" "" ""
.
.SH "NAME"
\fBfhc-embed\fR \-\- Build your Application for Embed Target
.
.SH "SYNOPSIS"
.
.nf
fhc embed <app\-id> [--env=<environment>]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to build an \'Embed\' version of your Application\.
.
.SH "Examples"
.
.nf
fhc embed mfLkParVTDcr80\-uEk8OhEfT \-\-live
.
.fi
