.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-ENDPOINTS" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-endpoints\fR \-\- FeedHenry Endpoints
.
.SH "SYNOPSIS"
.
.nf
fhc endpoints <app\-id> 
.
.fi
.
.SH "DESCRIPTION"
This is a utility command to see the various endpoints an App has\.
