.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-ENVIRONMENTS" "1" "April 2014" "" ""
.
.SH "NAME"
\fBfhc-environments\fR \-\- FeedHenry Environments
.
.SH "SYNOPSIS"
.
.nf
fhc environments
fhc environments [env]
fhc environments [env] resources
fhc environments [env] cache [flush]
fhc environments [env] cache [set] [type] [value] (where \'type\' is either \'percent\' or \'size\')
.
.fi
.
.SH "DESCRIPTION"
Show the FeedHenry Environments, and the Resources used by an Environment\.
.
.SH "Examples"
.
.nf
e\.g\. fhc environments dev
e\.g\. fhc environments dev resources
e\.g\. fhc environments dev cache flush
e\.g\. fhc environments dev cache set percent 50
e\.g\. fhc environments dev cache set size 524288000
.
.fi

