.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-FHCFG" "1" "November 2011" "" ""
.
.SH "NAME"
\fBfhc-fhcfg\fR \-\- Manage the fhc Configuration File
.
.SH "SYNOPSIS"
.
.nf
fhc fhcfg set <key> <value> [\-\-global]
fhc fhcfg get <key>
fhc fhcfg delete <key>
fhc fhcfg list
fhc fhcfg edit
.
.fi
.
.SH "DESCRIPTION"
fhc gets its configuration values from 5 sources, in this priority:
.
.IP "\(bu" 4
cli:
The command line flags\.  Putting \fB\-\-foo bar\fR on the command line sets the \fBfoo\fR configuration parameter to \fB"bar"\fR\|\.  A \fB\-\-\fR argument tells the cli
parser to stop reading flags\.  A \fB\-\-flag\fR parameter that is at the \fIend\fR of
the command will be given the value of \fBtrue\fR\|\.
.
.IP "\(bu" 4
env:
Any environment variables that start with \fBfhc_fhcfg_\fR will be interpreted
as a configuration parameter\.  For example, putting \fBfhc_fhcfg_foo=bar\fR in
your environment will set the \fBfoo\fR configuration parameter to \fBbar\fR\|\.  Any
environment configurations that are not given a value will be given the value
of \fBtrue\fR\|\.  Config values are case\-insensitive, so \fBFHCFG_FOO=bar\fR will
work the same\.
.
.IP "\(bu" 4
$HOME/\.fhcrc (or the \fBuserconfig\fR param, if set above):
This file is an ini\-file formatted list of \fBkey = value\fR parameters\.
.
.IP "\(bu" 4
$PREFIX/etc/fhcrc (or the \fBglobalconfig\fR param, if set above):
This file is an ini\-file formatted list of \fBkey = value\fR parameters
.
.IP "\(bu" 4
default configs:
This is a set of configuration parameters that are internal to fhc, and are
defaults if nothing else is specified\.
.
.IP "" 0
.
.SH "Sub\-commands"
fhcfg supports the following sub\-commands:
.
.SS "set"
.
.nf
fhc fhcfg set key value
.
.fi
.
.P
Sets the config key to the value\.
.
.P
If value is omitted, then it sets it to "true"\.
.
.SS "get"
.
.nf
fhc fhcfg get key
.
.fi
.
.P
Echo the config value to stdout\.
.
.SS "list"
.
.nf
fhc fhcfg list
.
.fi
.
.P
Show all the config settings\.
.
.SS "delete"
.
.nf
fhc fhcfg delete key
.
.fi
.
.P
Deletes the key from all configuration files\.
.
.SS "edit"
.
.nf
fhc fhcfg edit
.
.fi
.
.P
Opens the config file in an editor\.  Use the \fB\-\-global\fR flag to edit the
global config\.
.
.P
TODO!
.
.SH "Shorthands and Other CLI Niceties"
The following shorthands are parsed on the command\-line:
.
.IP "\(bu" 4
\fB\-v\fR: \fB\-\-version\fR
.
.IP "\(bu" 4
\fB\-h\fR, \fB\-?\fR, \fB\-\-help\fR, \fB\-H\fR: \fB\-\-usage\fR
.
.IP "\(bu" 4
\fB\-s\fR, \fB\-\-silent\fR: \fB\-\-loglevel silent\fR
.
.IP "\(bu" 4
\fB\-d\fR: \fB\-\-loglevel info\fR
.
.IP "\(bu" 4
\fB\-dd\fR, \fB\-\-verbose\fR: \fB\-\-loglevel verbose\fR
.
.IP "\(bu" 4
\fB\-ddd\fR: \fB\-\-loglevel silly\fR
.
.IP "\(bu" 4
\fB\-g\fR: \fB\-\-global\fR
.
.IP "\(bu" 4
\fB\-l\fR: \fB\-\-long\fR
.
.IP "\(bu" 4
\fB\-p\fR, \fB\-\-porcelain\fR: \fB\-\-parseable\fR
.
.IP "\(bu" 4
\fB\-v\fR: \fB\-\-version\fR
.
.IP "\(bu" 4
\fB\-f\fR: \fB\-\-force\fR
.
.IP "\(bu" 4
\fB\-l\fR: \fB\-\-long\fR
.
.IP "\(bu" 4
\fB\-desc\fR: \fB\-\-description\fR
.
.IP "\(bu" 4
\fBll\fR and \fBla\fR commands: \fBls \-\-long\fR
.
.IP "" 0
.
.P
If the specified configuration param resolves unambiguously to a known
configuration parameter, then it is expanded to that configuration
parameter\.  For example:
.
.IP "" 4
.
.nf
fhc ls \-\-par
# same as:
fhc ls \-\-parseable
.
.fi
.
.IP "" 0
.
.P
If multiple single\-character shorthands are strung together, and the
resulting combination is unambiguously not some other configuration
param, then it is expanded to its various component pieces\.  For
example:
.
.IP "" 4
.
.nf
fhc ls \-gpld
# same as:
fhc ls \-\-global \-\-parseable \-\-long \-\-loglevel info
.
.fi
.
.IP "" 0
.
.SH "Config Settings"
.
.SS "browser"
.
.IP "\(bu" 4
Default: OS X: \fB"open"\fR, others: \fB"google\-chrome"\fR
.
.IP "\(bu" 4
Type: String
.
.IP "" 0
.
.P
TODO \- The browser that is used to preview your web apps\.
.
.SS "cache"
.
.IP "\(bu" 4
Default: Windows: \fB~/fhc\-cache\fR, Posix: \fB~/\.fhc\fR
.
.IP "\(bu" 4
Type: path
.
.IP "" 0
.
.P
The location of fhc\'s cache directory\.  See \fBfhc help cache\fR
.
.SS "color"
.
.IP "\(bu" 4
Default: true
.
.IP "\(bu" 4
Type: Boolean or \fB"always"\fR
.
.IP "" 0
.
.P
If false, never shows colors\.  If \fB"always"\fR then always shows colors\.
If true, then only prints color codes for tty file descriptors\.
.
.SS "cookie"
.
.IP "\(bu" 4
Default: <blank>
.
.IP "\(bu" 4
Type: String
.
.IP "" 0
.
.P
The FeedHenry authentication cookie, this is set at login\.
.
.SS "editor"
.
.IP "\(bu" 4
Default: \fBEDITOR\fR environment variable if set, or \fB"vi"\fR
.
.IP "\(bu" 4
Type: path
.
.IP "" 0
.
.P
The command to run for \fBfhc edit\fR or \fBfhc config edit\fR\|\.
.
.SS "force"
.
.IP "\(bu" 4
Default: false
.
.IP "\(bu" 4
Type: Boolean
.
.IP "" 0
.
.P
Makes various commands more forceful\.
.
.IP "\(bu" 4
lifecycle script failure does not block progress\.
.
.IP "\(bu" 4
publishing clobbers previously published versions\.
.
.IP "\(bu" 4
skips cache when requesting from the registry\.
.
.IP "\(bu" 4
prevents checks against clobbering non\-fhc files\.
.
.IP "" 0
.
.SS "logfd"
.
.IP "\(bu" 4
Default: stderr file descriptor
.
.IP "\(bu" 4
Type: Number or Stream
.
.IP "" 0
.
.P
The location to write log output\.
.
.SS "loglevel"
.
.IP "\(bu" 4
Default: "warn"
.
.IP "\(bu" 4
Type: String
.
.IP "\(bu" 4
Values: "silent", "win", "error", "warn", "info", "verbose", "silly"
.
.IP "" 0
.
.P
What level of logs to report\.  On failure, \fIall\fR logs are written to \fBfhc\-debug\.log\fR in the current working directory\.
.
.SS "outfd"
.
.IP "\(bu" 4
Default: standard output file descriptor
.
.IP "\(bu" 4
Type: Number or Stream
.
.IP "" 0
.
.P
Where to write "normal" output\.  This has no effect on log output\.
.
.SS "parseable"
.
.IP "\(bu" 4
Default: false
.
.IP "\(bu" 4
Type: Boolean
.
.IP "" 0
.
.P
Output parseable results from commands that write to
standard output\. TODO \- investigate
.
.SS "proxy"
.
.IP "\(bu" 4
Default: "HTTP\fIPROXY" or "http\fRproxy" environment variable, or null
.
.IP "\(bu" 4
Type: url
.
.IP "" 0
.
.P
A proxy to use for outgoing http requests\.
.
.SS "feedhenry"
.
.IP "\(bu" 4
Default: https://apps\.feedhenry\.com/
.
.IP "\(bu" 4
Type: url
.
.IP "" 0
.
.P
The base URL of the FeedHenry server\.
.
.SS "tar"
.
.IP "\(bu" 4
Default: TAR environment variable, or "tar"
.
.IP "\(bu" 4
Type: path
.
.IP "" 0
.
.P
The tar executable
.
.SS "tmp"
.
.IP "\(bu" 4
Default: TMPDIR environment variable, or "/tmp"
.
.IP "\(bu" 4
Type: path
.
.IP "" 0
.
.P
Where to store temporary files and folders\.  All temp files are deleted
on success, but left behind on failure for forensic purposes\.
.
.SS "usage"
.
.IP "\(bu" 4
Default: false
.
.IP "\(bu" 4
Type: Boolean
.
.IP "" 0
.
.P
Set to show short usage output (like the \-H output)
instead of complete help when doing \fBfhc help\fR\|\.
.
.SS "username"
.
.IP "\(bu" 4
Default: null
.
.IP "\(bu" 4
Type: String
.
.IP "" 0
.
.P
The FeedHenry username\. Set with \fBfhc login\fR\|\.
.
.SS "userconfig"
.
.IP "\(bu" 4
Default: ~/\.fhcrc on Posix, or ~/fhc\-config on Windows
.
.IP "\(bu" 4
Type: path
.
.IP "" 0
.
.P
The location of user\-level configuration settings\.
.
.SS "version"
.
.IP "\(bu" 4
Default: false
.
.IP "\(bu" 4
Type: boolean
.
.IP "" 0
.
.P
If true, output the fhc version and exit successfully\.
.
.P
Only relevant when specified explicitly on the command line\.
.
.SS "viewer"
.
.IP "\(bu" 4
Default: "man"
.
.IP "\(bu" 4
Type: path
.
.IP "" 0
.
.P
The program to use to view help content\.
