.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-FHCFG" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-fhcfg\fR \-\- Manage the fhc Configuration File
.
.SH "SYNOPSIS"
.
.nf
fhc fhcfg set <key> <value> [\-\-global]
fhc fhcfg get <key>
fhc fhcfg delete <key>
fhc fhcfg list
fhc fhcfg edit
.
.fi
.
.SH "DESCRIPTION"
fhc gets its configuration values from 5 sources, in this priority:
.
.IP "\(bu" 4
cli:
The command line flags\.  Putting \fB\-\-foo bar\fR on the command line sets the \fBfoo\fR configuration parameter to \fB"bar"\fR\|\.  A \fB\-\-\fR argument tells the cli
parser to stop reading flags\.  A \fB\-\-flag\fR parameter that is at the \fIend\fR of
the command will be given the value of \fBtrue\fR\|\.
.
.IP "\(bu" 4
env:
Any environment variables that start with \fBfhc_fhcfg_\fR will be interpreted
as a configuration parameter\.  For example, putting \fBfhc_fhcfg_foo=bar\fR in
your environment will set the \fBfoo\fR configuration parameter to \fBbar\fR\|\.  Any
environment configurations that are not given a value will be given the value
of \fBtrue\fR\|\.  Config values are case\-insensitive, so \fBFHCFG_FOO=bar\fR will
work the same\.
.
.IP "\(bu" 4
$HOME/\.fhcrc (or the \fBuserconfig\fR param, if set above):
This file is an ini\-file formatted list of \fBkey = value\fR parameters\.
.
.IP "\(bu" 4
$PREFIX/etc/fhcrc (or the \fBglobalconfig\fR param, if set above):
This file is an ini\-file formatted list of \fBkey = value\fR parameters
.
.IP "\(bu" 4
default configs:
This is a set of configuration parameters that are internal to fhc, and are
defaults if nothing else is specified\.
.
.IP "" 0
.
.SH "Sub\-commands"
fhcfg supports the following sub\-commands:
.
.SS "set"
.
.nf
fhc fhcfg set key value
.
.fi
.
.P
Sets the config key to the value\.
.
.P
If value is omitted, then it sets it to "true"\.
.
.SS "get"
.
.nf
fhc fhcfg get key
.
.fi
.
.P
Echo the config value to stdout\.
.
.SS "list"
.
.nf
fhc fhcfg list
.
.fi
.
.P
Show all the config settings\.
.
.SS "delete"
.
.nf
fhc fhcfg delete key
.
.fi
.
.P
Deletes the key from all configuration files\.
.
.SS "edit"
.
.nf
fhc fhcfg edit
.
.fi
.
.P
Opens the config file in an editor\.  Use the \fB\-\-global\fR flag to edit the global config\.
