.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-FILES" "1" "July 2011" "" ""
.
.SH "NAME"
\fBfhc-files\fR \-\- Manage Application Files
.
.SH "SYNOPSIS"
.
.nf
fhc files list <app id>
fhc files read <file id>
fhc files update <app id> <file id> <file>
fhc files create <app id> <path> <name> <fileType>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to manage your FeedHenry application files\. 
