.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-GIT" "1" "November 2011" "" ""
.
.SH "NAME"
\fBfhc-git\fR \-\- FeedHenry App Git Actions
.
.SH "SYNOPSIS"
.
.nf
fhc git (props) <app id>
fhc git set <app id> <git prop name> <git prop value>
fhc git pull <app id>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to perform your Applications FeedHenry Git actions\.
