.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-HOSTS" "1" "July 2012" "" ""
.
.SH "NAME"
\fBfhc\-hosts\fR \- FeedHenry hosts
.
.SH "SYNOPSIS"
.
.nf

fhc hosts <app\-id>
.
.fi
.
.SH "DESCRIPTION"
This is a utility command to see the various hosts an App has\.
