.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-IMPORT" "1" "November 2011" "" ""
.
.SH "NAME"
\fBfhc-import\fR \-\- Import FeedHenry zipfile
.
.SH "SYNOPSIS"
.
.nf
fhc import <feedhenry zip file>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to an existing FeedHenry zipfile\.
