.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-INIT" "1" "April 2013" "" ""
.
.SH "NAME"
\fBfhc-init\fR \-\- Bootstrap a New Project
.
.SH "SYNOPSIS"
.
.nf
fhc init
.
.fi
.
.SH "DESCRIPTION"
Initialises a simple project structure in the current directory (if empty) by
pulling in a project template from GitHub\.
