.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-KEYS" "1" "April 2012" "" ""
.
.SH "NAME"
\fBfhc\-keys\fR \- Manage User or Application API Keys
.
.SH "SYNOPSIS"
.
.nf

fhc keys user list
fhc keys user create <key\-label>
fhc keys user update <key\-value> <new\-key\-label>
fhc keys user revoke <key\-value>
fhc keys user target [<key\-value>]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to manage your developer\'s API Keys\.
