.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-LOCAL" "1" "December 2012" "" ""
.
.SH "NAME"
\fBfhc-local\fR \-\- Creates Local Server For Local Development
.
.SH "SYNOPSIS"
.
.nf
fhc local [packages=<package[,package\.\.\.]>] [port=<port>] [cloudPort=<port>] [redisHost=<redisServer>] [redisPort=<redisPort>] [redisPassword=<password>]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to allow you to locally develop applications, the cloud portion of your app will be run locally by default\.  Before running this command, you should run fhc initlocal first, while connected to the Internet, to download some settings, scripts, and CSS files from our cloud platform\.
.
.P
This command must be run from the root of your app, i\.e\. the folder which contains your cloud, client and shared directories\.
.
.P
None of the parameters are required\. Just running "fhc local" will try to run the cloud code locally\.
.
.P
If your cloud code uses the $fh\.cache API, it will attempt to connect to a redis server accessible from your local machine\.  The defaults for the redis parameters are; host: 127\.0\.0\.1, port: 6379, password: ""
.
.SS "port"
The port you want to run the local client file server on\. This defaults to port 8000\.
.
.SS "cloudPort"
The port you want to run the local cloud server on\. This defaults to port 8001\.
.
.SS "packages"
A list of comma seperated packages that you want to be applied
.
.SH "Example"
fhc local packages=ios,iphone
