.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-LOCAL" "1" "July 2012" "" ""
.
.SH "NAME"
\fBfhc-local\fR \-\- Creates Local Server For Local Development
.
.SH "SYNOPSIS"
.
.nf
fhc local app=<appId> domain=<domain> port=<port> package=<package>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to allow you to locally develop applications and still make calls to the FH cloud\.
