.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-LOCAL" "1" "July 2012" "" ""
.
.SH "NAME"
\fBfhc\-local\fR \- Creates Local Server For Local Development
.
.SH "SYNOPSIS"
.
.nf

fhc local proxy=<true|false> watch=<true|false> app=<appId> packages=<package[,package\|\.\|\.\|\.]> domain=<domain> port=<port>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to allow you to locally develop applications and still make calls to the FH cloud\. It must be run from the root of your app( i\.e\. the folder which contains your cloud, client and shared directories)
.
.P
None of the parameters are required\. Just running "fhc local" will try to run the cloud code locally\.
.
.SS "proxy"
Specifies whether act calls will be proxied through to the app specified or handled locally\. Only node\.js based apps can be handled locally\. If proxy is false no other parameters are required
.
.SS "app"
the alias or guid to tell the server what app to proxy the cloud calls to
.
.SS "domain"
The domain where your app is hosted\. Defaults to your current target\.
.
.SS "port"
The port you want to run the local server on\. Defaults to port 8888
.
.SS "packages"
A list of comma seperated packages that you want to be applied
.
.SS "watch"
If you are running cloud code locally (i\.e proxy=false), watch specifes whether or not you want the code to be reloaded automatically when a file is modified\. Defaults to true\.
.
.SH "Example"
fhc local proxy=true domain=apps app=lfablwq3bflabd_guias_ packages=ios,iphone
