.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-LOGIN" "1" "May 2011" "" ""
.
.SH "NAME"
\fBfhc-login\fR \-\- Login to FeedHenry
.
.SH "SYNOPSIS"
.
.nf
fhc login <username> <password>
.
.fi
.
.SH "DESCRIPTION"
If none are provided, the username and password are read in from prompts\.
.
.SH "CONFIGURATION"
.
.SS "feedhenry"
Default: http://apps\.feedhenry\.com
.
.P
The FeedHenry base URL\.
