.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-LOGS" "1" "October 2014" "" ""
.
.SH "NAME"
\fBfhc-logs\fR \-\- FeedHenry Application Log Files
.
.SH "SYNOPSIS"
.
.nf
fhc logs [get] <app\-id> [log\-name] \-\-env=<environment>
fhc logs tail <app\-id> [last\-N\-lines] [offset\-from] [log\-name] \-\-env=<environment>
fhc logs list <app\-id> \-\-env=<environment>
fhc logs delete <app\-id> <log\-name> \-\-env=<environment>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to list/retrieve/delete/tail your Application log files\.
.
.P
Note: log tail defaults to the current std\-out log file & display last 1000 lines of log file\. To specify an offset, pass \-1 for the last\-N\-lines param\. e\.g\.
.
.IP "" 4
.
.nf
fhc logs tail \-1 12345
.
.fi
.
.IP "" 0
.
.P
This will return all log entries from position 12345 onwards\.
.
.SH "EXAMPLES"
.
.nf
fhc logs mfLkParVTDcr80\-uEk8OhEfT \-\-env=dev
.
.fi

