.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-LOGS" "1" "November 2011" "" ""
.
.SH "NAME"
\fBfhc-logs\fR \-\- FeedHenry Application Log Files
.
.SH "SYNOPSIS"
.
.nf
fhc logs <app id> \-\-live
.
.fi
.
.SH "DESCRIPTION"
This command can be used to retrieve your Application log files\. Use the \-\-live switch if your app is staged to the live FeedHenry deployment environment\.
