.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-LOGS" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-logs\fR \-\- FeedHenry Application Log Files
.
.SH "SYNOPSIS"
.
.nf
fhc logs [get] <app\-id> [log\-name] [\-\-live]
fhc logs list <app\-id> [\-\-live]
fhc logs delete <app\-id> <log\-name> [\-\-live]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to list/retrieve/delete your Application log files\. Use the \-\-live switch if your app is staged to the live FeedHenry deployment environment\.
.
.SH "EXAMPLES"
.
.nf
fhc logs mfLkParVTDcr80\-uEk8OhEfT \-\-live
.
.fi

