.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-MAS\-APPSTORE" "1" "October 2012" "" ""
.
.SH "NAME"
\fBfhc-mas-appstore\fR \-\- View your Mobile App Store
.
.SH "SYNOPSIS"
.
.nf
fhc mas\-appstore getstoreitems
fhc admin\-appstore read
.
.fi
.
.SH "DESCRIPTION"
This command allows you to View your FeedHenry Mobile App Store\. See http://docs\.feedhenry\.com/v2/mas\.html for more information\.
