.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-NATIVE" "1" "April 2012" "" ""
.
.SH "NAME"
\fBfhc\-native\fR \- FeedHenry Actions
.
.SH "SYNOPSIS"
.
.nf

fhc native config=<apple|android> app=<app\-id | alias> [dir=<dir to write to>]
.
.fi
.
.SH "DESCRIPTION"
This is a utility command create the config file required by the different native libraries
.
.SS "config"
the platform to create the config file for
.
.SS "app"
the alias or guid to use in creating the config
.
.SS "dir"
An optional dir to write the file to\. This is for use on the command line\. If you don\'t specify a dir or writing to the dir faile, the config will be outputted to the terminal\.
.
.SH "EXAMPLES"
.
.nf

fhc native config=apple app=c0TPJtvFbztuS2p7NhZN3oZz dir=/Users/me/Documents
.
.fi

