.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-NOTIFICATIONS" "1" "October 2014" "" ""
.
.SH "NAME"
\fBfhc-notifications\fR \-\- List notifications of a FeedHenry App
.
.SH "SYNOPSIS"
.
.nf
fhc notifications [list] <app\-guid> \-\-env=<environment>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to list or dismiss notification messages of a FeedHenry Application\.
