.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-NOTIFICATIONS" "1" "July 2013" "" ""
.
.SH "NAME"
\fBfhc-notifications\fR \-\- List notifications of a FeedHenry App
.
.SH "SYNOPSIS"
.
.nf
fhc notifications [list] <app\-guid> [\-\-live]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to list or dismiss notification messages of a FeedHenry Application\. By default it will list the notifications for the "dev" environment\. If the "\-\-live" flag is set the notifications for the live environment will be returned\.
