.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-PING" "1" "April 2012" "" ""
.
.SH "NAME"
\fBfhc\-ping\fR \- Ping a FeedHenry Application
.
.SH "SYNOPSIS"
.
.nf

fhc ping <app\-id> [\-\-live]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to ping a FeedHenry Application\.
