.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-PING" "1" "July 2011" "" ""
.
.SH "NAME"
\fBfhc-ping\fR \-\- Pings the FeedHenry URL
.
.SH "SYNOPSIS"
.
.nf
fhc ping
.
.fi
.
.SH "DESCRIPTION"
This command will ping FeedHenry\. Note: a random number is returned from the FeedHenry ping API call\.
