.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-PREVIEW" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc\-preview\fR \- FeedHenry Application Preview
.
.SH "SYNOPSIS"
.
.nf

fhc preview [show] <app\-id>
fhc preview url <app\-id>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to preview your application in your browser\. By default, the \'open\' command is the default command used on OSX to open the preview url, otherwise \'google\-chrome\' is the default command\.
.
.P
To set your default brower: fhc set browser firefox Or on windows: fhc set browser start
.
.SH "EXAMPLES"
.
.nf

fhc preview mfLkParVTDcr80\-uEk8OhEfT
.
.fi

