.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-PREVIEW" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-preview\fR \-\- FeedHenry Application Preview
.
.SH "SYNOPSIS"
.
.nf
fhc preview [url] <app\-id>
fhc preview show <app\-id> 
.
.fi
.
.SH "DESCRIPTION"
This command can be used to preview your application in your browser\.
.
.SH "EXAMPLES"
.
.nf
fhc preview url mfLkParVTDcr80\-uEk8OhEfT
.
.fi

