.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-READ" "1" "April 2012" "" ""
.
.SH "NAME"
\fBfhc\-read\fR \- Read FeedHenry Application Proprties
.
.SH "SYNOPSIS"
.
.nf

fhc read <app\-id>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to read a FeedHenry Application\'s Properties\.
