.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-READ" "1" "April 2012" "" ""
.
.SH "NAME"
\fBfhc-read\fR \-\- Read FeedHenry Application Proprties
.
.SH "SYNOPSIS"
.
.nf
fhc read <app\-id> 
.
.fi
.
.SH "DESCRIPTION"
This command can be used to read a FeedHenry Application\'s Properties\.
