.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-RESOURCES" "1" "October 2012" "" ""
.
.SH "NAME"
\fBfhc\-resources\fR \- List resources for a FeedHenry Applications
.
.SH "SYNOPSIS"
.
.nf

fhc resources <appId>
fhc resources <appId> \-\-live
.
.fi
.
.SH "DESCRIPTION"
Show the resources available and being used by a FeedHenry application, either in the \'dev\' or \'live\' FeedHenry environment\.
.
.SH "Examples"
.
.nf

fhc resources mfLkParVTDcr80\-uEk8OhEfT \-\-live
.
.fi

