.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-RESTART" "1" "October 2014" "" ""
.
.SH "NAME"
\fBfhc-restart\fR \-\- Restart a FeedHenry Application
.
.SH "SYNOPSIS"
.
.nf
fhc restart <app\-id> [\-\-env=<environment>]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to restart a FeedHenry Application\.
