.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-RESTART" "1" "January 2013" "" ""
.
.SH "NAME"
\fBfhc-restart\fR \-\- Restart a FeedHenry Application
.
.SH "SYNOPSIS"
.
.nf
fhc restart <app\-id> [\-\-live]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to restart a FeedHenry Application\.
