.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-SEARCH" "1" "December 2011" "" ""
.
.SH "NAME"
\fBfhc\-search\fR \- Search FeedHenry Applications
.
.SH "SYNOPSIS"
.
.nf

fhc search <query>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to search your FeedHenry applications\.
.
.SH "EXAMPLES"
.
.nf

fhc search "node"
.
.fi

