.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-SEARCH" "1" "November 2011" "" ""
.
.SH "NAME"
\fBfhc-search\fR \-\- Search FeedHenry Applications
.
.SH "SYNOPSIS"
.
.nf
fhc apps search <query>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to search your FeedHenry applications\.
