.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-SECUREENDPOINTS" "1" "December 2012" "" ""
.
.SH "NAME"
\fBfhc\-secureendpoints\fR \- Manage an Apps Secure Endpoints
.
.SH "SYNOPSIS"
.
.nf

fhc secureendpoints [get] <app\-id> [\-\-live]
fhc secureendpoints set\-default <app\-id> <default> [\-\-live]
fhc secureendpoints set\-override <app\-id> <endpoint> <default> [\-\-live]
fhc secureendpoints remove\-override <app\-id> <endpoint> [\-\-live]
where \'default\' can be either \'https\' or \'appapikey\'\. Use \'fhc appendpoints\' to list an Apps endpoints\.
.
.fi
.
.SH "DESCRIPTION"
Manage the Secure Endpoints for an App\. See http://docs\.feedhenry\.com/v2/secureendpoints_api\.html for more information\.
.
.SH "Examples"
.
.nf

fhc secureendpoints mfLkParVTDcr80\-uEk8OhEfT \-\-live
.
.fi

