.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-STAGE" "1" "November 2011" "" ""
.
.SH "NAME"
\fBfhc-stage\fR \-\- Stage FeedHenry Applications
.
.SH "SYNOPSIS"
.
.nf
fhc stage <appId> 
fhc stage <appId> \-\-live
.
.fi
.
.SH "DESCRIPTION"
This command can be used to stage your FeedHenry applications, either to the \'development\' or \'live\' FeedHenry environment\.
.
.P
e\.g\. 
fhc stage mfLkParVTDcr80\-uEk8OhEfT \-\-live
