.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-START" "1" "January 2013" "" ""
.
.SH "NAME"
\fBfhc-start\fR \-\- Start a FeedHenry Application
.
.SH "SYNOPSIS"
.
.nf
fhc start <app\-id> [\-\-live]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to start a FeedHenry Application\.
