.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-START" "1" "October 2014" "" ""
.
.SH "NAME"
\fBfhc-start\fR \-\- Start a FeedHenry Application
.
.SH "SYNOPSIS"
.
.nf
fhc start <app\-id> \-\-env=<environment>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to start a FeedHenry Application\.
