.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-STATS" "1" "October 2014" "" ""
.
.SH "NAME"
\fBfhc-stats\fR \-\- FeedHenry Stats
.
.SH "SYNOPSIS"
.
.nf
fhc stats <app\-id> <stats\-type> <num\-results> \-\-env=<environment>
.
.fi
.
.SH "DESCRIPTION"
Get App stats from your FeedHenry Application\.
.
.SS "app id"
Your application id\.
.
.SS "stats\-type"
Type of stats\. Options here are \'api\' (in\-built system stats, e\.g\. timing app end points, etc) or \'app\' (stats a developer has put in their code using feedhenry\.stats() API)\.
.
.SS "num\-results"
Number of results you want returned\. Numeric value\.
.
.SS "\-\-env=&lt;environment&gt;"
Use \-\-env=<environment> to see stats from your app staged in another environment\.
.
.SH "EXAMPLES"
.
.nf
fhc stats h2n0pg\-qvar407mijmsvbapz app 10 \-\-env=live
.
.fi

