.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-STOP" "1" "October 2014" "" ""
.
.SH "NAME"
\fBfhc-stop\fR \-\- Stop a FeedHenry Application
.
.SH "SYNOPSIS"
.
.nf
fhc stop <app\-id> [\-\-env=<environment>]
.
.fi
.
.SH "DESCRIPTION"
This command can be used to stop a FeedHenry Application\.
