.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-TARGETS" "1" "September 2011" "" ""
.
.SH "NAME"
\fBfhc-targets\fR \-\- List the stored FeedHenry Targets
.
.SH "SYNOPSIS"
.
.nf
fhc targets
.
.fi
.
.SH "DESCRIPTION"
This command will list all the FeedHenry Targets, i\.e\. successful logins\. 
