.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-TARGET" "1" "August 2011" "" ""
.
.SH "NAME"
\fBfhc-target\fR \-\- Get/Set the FeedHenry Target URL
.
.SH "SYNOPSIS"
.
.nf
fhc target
fhc target <feedhenry url>
fhc target <feedhenry url> <user> <password>
.
.fi
.
.SH "DESCRIPTION"
This command will get or set the FeedHenry Target URL\. E\.g\. fhc target https://apps\.feedhenry\.com
