.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-TEMPLATES" "1" "December 2011" "" ""
.
.SH "NAME"
\fBfhc\-templates\fR \- Use FeedHenry Templates
.
.SH "SYNOPSIS"
.
.nf

fhc templates
fhc templates (list)
fhc templates (read) <template id>
fhc templates init <template id>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to work with FeedHenry templates\.
