.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "FHC\-TEMPLATES" "1" "April 2014" "" ""
.
.SH "NAME"
\fBfhc-templates\fR \-\- FeedHenry Templates
.
.SH "SYNOPSIS"
.
.nf
fhc templates apps [<template\-id]
fhc templates projects [<template\-id>]
.
.fi
.
.SH "DESCRIPTION"
View App and Projects Templates in FeedHenry\. Each Template can be used when creating a new Project/App\. See \fBfhc help create\fR\|\.
