.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-TEMPLATES" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-templates\fR \-\- Use FeedHenry Templates
.
.SH "SYNOPSIS"
.
.nf
fhc templates 
fhc templates [list]
fhc templates [read] <template\-id>
fhc templates init <template\-id>
.
.fi
.
.SH "DESCRIPTION"
This command can be used to work with FeedHenry templates\.
