.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-UPDATE" "1" "April 2012" "" ""
.
.SH "NAME"
\fBfhc\-update\fR \- Update a FeedHenry Application Properties
.
.SH "SYNOPSIS"
.
.nf

fhc update <app\-id> <property\-name> <property\-value>"
.
.fi
.
.SH "DESCRIPTION"
This command can be used to update FeedHenry Application properties\.
