.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-UPDATE" "1" "April 2012" "" ""
.
.SH "NAME"
\fBfhc-update\fR \-\- Update a FeedHenry Application Properties
.
.SH "SYNOPSIS"
.
.nf
fhc update <app\-id> <property\-name> <property\-value>"
.
.fi
.
.SH "DESCRIPTION"
This command can be used to update FeedHenry Application properties\.
