.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-USER" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc-user\fR \-\- FeedHenry User Information
.
.SH "SYNOPSIS"
.
.nf
fhc user 
.
.fi
.
.SH "DESCRIPTION"
This command will return FeedHenry information about the logged in user\.
