.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FHC\-VERSION" "1" "February 2012" "" ""
.
.SH "NAME"
\fBfhc\-version\fR \- FeedHenry Version Information
.
.SH "SYNOPSIS"
.
.nf

fhc version
fhc version <FeedHenry\-URL>
.
.fi
.
.SH "DESCRIPTION"
This command will return the FeedHenry Version Information of the current FeedHenry Target (or the FeedHenry URL specified)\.
