.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FHC\-VERSION" "1" "December 2011" "" ""
.
.SH "NAME"
\fBfhc-version\fR \-\- FeedHenry Version Information
.
.SH "SYNOPSIS"
.
.nf
fhc version 
fhc version <FeedHenry URL>
.
.fi
.
.SH "DESCRIPTION"
This command will return the FeedHenry Version Information of the current FeedHenry Target (or the FeedHenry URL specified)\.
